import PDFDocument from "pdfkit";
import { Readable } from "stream";

export interface DrawResult {
  participantName: string;
  teamName: string;
  teamFlag: string;
  teamGroup: string;
}

export interface LeaderboardEntry {
  rank: number;
  participantName: string;
  teamName: string;
  teamFlag: string;
  teamGroup: string;
  points: number;
  stage: string;
}

export async function generatePoolPDF(
  poolName: string,
  drawResults: DrawResult[],
  leaderboard: LeaderboardEntry[]
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: "A4",
      margin: 40,
    });

    const chunks: Buffer[] = [];

    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    // Title
    doc.fontSize(28).font("Helvetica-Bold").text("🏆 World Cup Sweepstake", { align: "center" });
    doc.fontSize(16).font("Helvetica").text(poolName, { align: "center", margin: [10, 0, 20, 0] });

    // Draw Results Section
    doc.fontSize(14).font("Helvetica-Bold").text("Draw Results", { margin: [20, 0, 10, 0] });

    const resultsPerRow = 3;
    let currentRow = 0;
    let xOffset = 40;
    const yStart = doc.y;

    drawResults.forEach((result, index) => {
      if (index > 0 && index % resultsPerRow === 0) {
        currentRow++;
        xOffset = 40;
      }

      const x = xOffset + (index % resultsPerRow) * 150;
      const y = yStart + currentRow * 80;

      // Draw box
      doc
        .rect(x, y, 140, 70)
        .stroke()
        .fontSize(10)
        .font("Helvetica-Bold")
        .text(result.participantName, x + 5, y + 5, { width: 130 });

      doc.fontSize(24).text(result.teamFlag, x + 5, y + 20);

      doc
        .fontSize(9)
        .font("Helvetica-Bold")
        .text(result.teamName, x + 5, y + 45, { width: 130 });

      doc.fontSize(8).font("Helvetica").text(result.teamGroup, x + 5, y + 58, { width: 130 });
    });

    // Move down for leaderboard
    doc.moveDown(Math.ceil(drawResults.length / resultsPerRow) * 5);

    // Leaderboard Section
    doc.fontSize(14).font("Helvetica-Bold").text("Live Leaderboard", { margin: [20, 0, 10, 0] });

    // Table header
    const tableTop = doc.y + 10;
    const col1 = 50;
    const col2 = 150;
    const col3 = 280;
    const col4 = 380;
    const col5 = 480;

    doc
      .fontSize(10)
      .font("Helvetica-Bold")
      .text("#", col1, tableTop)
      .text("Participant", col2, tableTop)
      .text("Team", col3, tableTop)
      .text("Stage", col4, tableTop)
      .text("Points", col5, tableTop);

    // Table rows
    let rowY = tableTop + 20;
    leaderboard.forEach((entry) => {
      doc
        .fontSize(9)
        .font("Helvetica")
        .text(entry.rank.toString(), col1, rowY)
        .text(entry.participantName, col2, rowY)
        .text(`${entry.teamFlag} ${entry.teamName}`, col3, rowY)
        .text(entry.stage, col4, rowY)
        .text(entry.points.toString(), col5, rowY);

      rowY += 15;
    });

    // Footer
    doc
      .fontSize(8)
      .font("Helvetica")
      .text("Generated by Sweepstake Pro", 50, doc.page.height - 50, { align: "center" });

    doc.end();
  });
}
